### ISSUE TITLE
TEST_TIMESTEMP fails on macOS builds on CI

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#1193]
For example here: 
https://github.com/gnudatalanguage/gdl/runs/4182034052?check_suite_focus=true

```
 176/191 Test #176: test_timestamp.pro .................***Failed    0.86 sec
% Compiled module: TEST_TIMESTAMP.
% TIMESTAMP: DAY must contain numbers between 1 and 31.
% TIMESTAMP: HOUR must contain numbers between 0 and 23.
% Compiled module: ERRORS_ADD.
% TEST_TIMESTAMP: Error on operation : Error 4
% Compiled module: BANNER_FOR_TESTSUITE.
% Compiled module: GDL_IDL_FL.
% TEST_TIMESTAMP: ======================================================
% TEST_TIMESTAMP: =                                                    =
% TEST_TIMESTAMP: =  1 errors encountered during TEST_TIMESTAMP tests  =
% TEST_TIMESTAMP: =                                                    =
% TEST_TIMESTAMP: ======================================================

```

**Comment by slayoo** [comment]
temporarily disabled the test: https://github.com/gnudatalanguage/gdl/pull/1182

**Comment by GillesDuvert** [comment]
test_timestamp is OK when run manually on my side.
similarly, [some recent jobs were failing on test_routine_names ](https://github.com/gnudatalanguage/gdl/runs/4172232948?check_suite_focus=true), but test_routine_names is OK when run manually. I simply resubmitted the PT and it passes now. Go figure.

Would it be possible to somehow trap the failed tests and redo them in verbose mode? Or even better, using a debugger that could give a traceback?

**Comment by pjb7687** [comment]
I am testing this on the interactive terminal session, and I found that on macOS:
```
GDL> ts = TIMESTAMP(YEAR = 2012, MONTH = 9, $
   DAY = 4, HOUR = 11, MINUTE = 25, SECOND = 15)
GDL> ts
2012-09-04T11:25:15-01:55
GDL>
```

**Comment by pjb7687** [comment]
Fixed: https://github.com/gnudatalanguage/gdl/commit/2d4219a18639369fd67c155f42bd475ab0feed41

I don't know why it didn't fail in the other environments - it should also fail!

**Comment by pjb7687** [comment]
and also I returned the `test_timestamp` to `testsuite`..

**Comment by slayoo** [comment]
Thanks!

BTW
> Would it be possible to somehow trap the failed tests and redo them in verbose mode? Or even better, using a debugger that could give a traceback?

Since last week, "mae test" is now run on CI with the CTEST_OUTPUT_ON_FAILURE=1 , so anything printed from GDL code in a failing code is now visible in the output logs of GA:
https://github.com/gnudatalanguage/gdl/commit/0b416908d2a03ee7fbdce668d7c31fae6b5b448c#diff-cd495307171e650f59aab7e02f88c17d00a4eea082208cabdfc7abf92ac5592e

**Comment by slayoo** [comment]
> and also I returned the test_timestamp to testsuite..
but it is still not in the LIST file, right? Only tests listed there are executed (which is unintuitive given we anyhow have separate directories for tests to be executed and not...)

**Comment by slayoo** [comment]
https://github.com/gnudatalanguage/gdl/pull/1198
